//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public int Source { get; set; }
        public int Destination { get; set; }
        public int CargoId { get; set; }
        public Nullable<System.DateTime> Departure_Time { get; set; }
        public Nullable<System.DateTime> Arrival_Time { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
